Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/ubuntu-24.04"
  config.vm.hostname = "ansible-node"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-ansible"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
  SHELL
end
