apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web2
  name: web2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kubernetes-default: "true"
        io.kompose.service: web2
    spec:
      containers:
        - image: nginx
          name: web2
          resources: {}
      restartPolicy: Always
status: {}
