global:
  scrape_interval: 15s          # Intervalo de recolección de métricas
  evaluation_interval: 15s      # Frecuencia de evaluación de reglas

  external_labels:
    monitor: 'monitoring-stack' # Etiqueta global para todas las métricas

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          instance: 'Servidor Ubuntu'
  - job_name: 'otros_nodos'
    static_configs:
      - targets: ['192.168.1.148:9100']
        labels:
          instance: 'Servidor Físico'
