version: '3.8'

services:
  calculadora:
    build: .
    container_name: calculadora-compose
    command: python3 -m unittest test_calculadora.py
    volumes:
      - .:/app
    working_dir: /app
