pipeline {
    agent any

    triggers {
        pollSCM('* * * * *') // Revisa cambios cada minuto (para pruebas)
    }

    stages {
        stage('Preparar entorno') {
            steps {
                echo 'Entorno listo para pruebas.'
            }
        }

        stage('Pruebas Unitarias') {
            steps {
                // Ejecuta todos los tests dentro de la carpeta tests
                sh 'python3 -m unittest discover -s tests -p "test_*.py"'
            }
        }
    }

    post {
        success {
            echo 'Pipeline ejecutado correctamente.'
        }
        failure {
            echo 'La pipeline ha fallado. Revisar errores.'
        }
    }
}
